name = "discord-vote-site"
compatibility_date = "2026-01-01"

# Cloudflare Pages output (your frontend)
pages_build_output_dir = "."

# -----------------------
# D1 DATABASE (YOU PROVIDED THIS)
# -----------------------
[[d1_databases]]
binding = "DB"
database_name = "votes_db"
database_id = "7f9caacd-53a8-444d-8e8f-c44bbf1a595f"

# -----------------------
# ENV VARIABLES (DISCORD OAUTH)
# -----------------------
[vars]
DISCORD_CLIENT_ID = "1514619949887393874"
DISCORD_CLIENT_SECRET = "7rX-yakrJ8PJpfCDIJErnX6Yd-HBa7V-"
DISCORD_REDIRECT_URI = "https://vote-zhp.pages.dev/auth/callback"
DISCORD_INVITE = "https://discord.gg/Yb7Hydn6th"
